### ISSUE TITLE
Difference results with G-NIA

### ISSUE THREAD

**Issue by shanzhiq** [jumxglhf/G2A2C#1]
Thanks for your wonderful Job. However, Why the result in G-NIA different so much with your results when in black box condition

**Comment by jumxglhf** [comment]
Hi!

Thanks for your interest in our work!

Our reproduced results for G-NIA are sometimes even stronger than the performance reported in the original paper. To answer your question, one reason could be different data splits we use for citeseer (G-NIA explores a supervised setting; whereas we use the semi-supervised setting with public split). For Reddit and OGB-Prod. where our framework utilizes the same splits as G-NIA did, I feel like that the results reported in G-NIA align with ours. 

Please let me know if you have any further problems!

**Comment by shanzhiq** [comment]
oh, I understand why now, thanks you
